# Generated by Django 5.1.1 on 2024-10-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion_app', '0002_alter_utilisateur_options_alter_utilisateur_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Les groupes auxquels cet utilisateur appartient. Un utilisateur obtiendra tous les permissions accordées à chacun de ses groupes.', related_name='utilisateur_set', to='auth.group', verbose_name='Groupes'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions spécifiques pour cet utilisateur.', related_name='utilisateur_set', to='auth.permission', verbose_name='Permissions utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Médecin'), ('ong', 'ONG'), ('donor', 'Donateur'), ('admin', 'Administrateur')], default='donor', max_length=10),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
