# Generated by Django 5.1.1 on 2024-10-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0004_alter_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A-', 'A-'), ('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='statut',
            field=models.CharField(blank=True, choices=[('Diagnostic positif', 'Diagnostic positif'), ('Exposition au VIH', 'Exposition au VIH')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Médecin'), ('ong', 'ONG')], max_length=10),
        ),
    ]
