# Generated by Django 5.1.1 on 2024-10-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0005_alter_enfant_groupe_sanguin_alter_enfant_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=10, null=True),
        ),
    ]
