# Generated by Django 5.1.1 on 2024-10-29 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0006_enfant_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='inscrit_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants_inscrits', to=settings.AUTH_USER_MODEL),
        ),
    ]
