# Generated by Django 5.1.1 on 2024-10-30 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0007_enfant_inscrit_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='ong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to=settings.AUTH_USER_MODEL),
        ),
    ]
