# Generated by Django 5.1.1 on 2025-04-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0009_medecin_ong_enfant_date_enregistrement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant',
            name='pays',
            field=models.CharField(blank=True, choices=[("Cote d'Ivoire", "Cote d'Ivoire")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enfant',
            name='ville',
            field=models.CharField(blank=True, choices=[('Abidjan', 'abidjan'), ('Yamoussoukro', 'Yamoussoukro'), ('Bouake', 'Bouake'), ('korogho', 'korogho')], max_length=20, null=True),
        ),
    ]
