# Generated by Django 5.1.1 on 2025-04-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0010_enfant_pays_enfant_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant',
            name='statut',
        ),
        migrations.AddField(
            model_name='enfant',
            name='stade',
            field=models.CharField(blank=True, choices=[('VIH', 'VIH '), ('SIDA', 'SIDA')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enfant',
            name='type',
            field=models.CharField(blank=True, choices=[('Enfants', 'Enfants'), ('Orphelins', 'Orphelins')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
    ]
