# Generated by Django 5.1.1 on 2025-04-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0011_remove_enfant_statut_enfant_stade_enfant_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfant',
            old_name='type',
            new_name='typee',
        ),
    ]
