# Generated by Django 5.1.1 on 2025-04-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_app', '0013_remove_enfant_typee_enfant_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moyen_paiement', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('virement_bancaire', 'Virement Bancaire'), ('espece', 'Espèce')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('date_don', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
